#+TITLE:     IMA: An R package for high-throughput analysis of Illumina’s 450K Infinium methylation data
#+AUTHOR:    Dan Wang   
#+EMAIL:     dan.wang@roswellpark.org 
#+DATE:      2011-08-18 Thu
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

* Abstract
The Illumina Infinium HumanMethylation450 BeadChip is a newly designed high-density microarray for quantifying the methylation level of over 450,000 CpG sites within human genome. IMA (Illumina Methylation Analyzer) is a computational package designed to automate the pipeline for analyzing site-level and region-level methylation changes in epigenetic studies utilizing the 450K DNA methylation microarray. The pipeline loads the data from Illumina platform and provides user-customized functions commonly required to perform differential methylation analysis for individual sites as well as annotated regions.

* Installation 
Option1: use following command in R:

install.packages("IMA", repos="http://R-Forge.R-project.org")##Currently not available

Option2: download the package [[./IMA_1.2.2.tar.gz][here]] and install in R by:

install.packages("IMA_1.2.2.tar.gz",repos=NULL)


* Tutorial
A vignentte that illustrate various aspects of IMA is available [[./meth450.pdf][here]]
  
The user manual of IMA package could be found [[./IMA-manual.pdf][here]].
* Annotation file

The 11 region level annotation for the 450k sites without any filtering could be download from [[./fullannotInd.rda][here]].

To load it, just type the following command in R after download:

load("./fullannotInd.rda")
* Pipeline

The [[./pipeline.R][pipeline]] loads the data from Illumina platform and provides user-customized functions commonly required to perform differential methylation analysis for individual sites as well as annotated regions. The user can either run the pipeline with default setting or specify optional routes in the parameter file.

To run the pipeline file, just simply type "R no save <pipeline.R" under Linux/Unix. Alternatively, paste the commandes in the pipeline.R into R.

* Project summary
The project summary page you can find [[http://r-forge.r-project.org/projects/IMA/][here]].
