#+TITLE:     IMA: An R package for high-throughput analysis of Illumina’s 450K Infinium methylation data
#+AUTHOR:    Dan Wang ; Song Liu  
#+EMAIL:     dan.wang@roswellpark.org ; song.liu@roswellpark.org
#+DATE:      2011-08-18 Thu
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

* Abstract
The recently released Infinium HumanMethylation450 BeadChip provides an unprecedented opportunity to quantify the methylation level of over 450,000 CpG sites within human genome. IMA (Illumina Methylation Analyzer) is a package designed to automate the pipeline for analyzing site-level and region-level methylation changes in epigenetic studies utilizing the 450K DNA methylation microarray. The pipeline loads the data from Illumina platform and provides user-customized functions commonly required to perform differential methylation analysis for individual sites as well as annotated regions. We showed that region-level analysis might complement site-level analysis in differential methylation inference.

* Installation 
install.packages("IMA", repos="http://R-Forge.R-project.org")

**Prerequisites: 

The IMA package requires the following packages to be installed: WriteXLS,GSA,limma,dplR,MASS,bioDist,heatmap.2.
If your system does not have them installed, the easiest way to install them is to issue the following command at the R prompt:

install.packages(c("WriteXLS","GSA","limma","dplR","MASS","bioDist","heatmap.2"))
* Tutorial
  A vignentte that illustrate various aspects of IMA is available and it can be found [[./meth450.pdf][here]]
* Pipeline
It will automatically produce the unsuperwised cluster tree, test results in excel file and saved the result into Rdata for further explor.
The [[./pipeline.R][pipeline]] file can be used to run with default setting or specify options in it.

To run the pipeline file, just simply type "R no save <pipeline.R" under Linux/Unix. Alternatively, paste the commandes in the pipeline.R into R.
* Annotation file
The 11 region level annotation for the 450k sites without any filtering could be download from [[./fullannotInd.rda][here]].  

To load it, just type the following command in R after download:

load("./fullannotInd.rda")
* Project summary
The project summary page you can find [[http://r-forge.r-project.org/projects/IMA/][here]].
